//! Bridge code generation — comptime TypeScript type declarations for bridge
//! commands.
//!
//! This is a pure Zig module that inspects bridge command signatures and emits
//! TypeScript `.d.ts` declarations. No external tooling is needed.
//!
//! Usage:
//! ```zig
//! const codegen = @import("bridge/codegen.zig");
//! const ts = try codegen.generateTypeScript(allocator, &.{
//!     codegen.defineCommand("add", &.{
//!         .{ .name = "a", .type_name = "number" },
//!         .{ .name = "b", .type_name = "number" },
//!     }, "number"),
//! });
//! defer allocator.free(ts);
//! ```

const std = @import("std");

/// Describes a single bridge command.
pub const CommandSchema = struct {
    name: []const u8,
    params: []const ParamSchema,
    /// JSON type name: "void", "string", "number", "object"
    result: []const u8,
};

/// Describes a single parameter of a bridge command.
pub const ParamSchema = struct {
    name: []const u8,
    type_name: []const u8,
    optional: bool = false,
};

/// Helper to define a command inline.
pub fn defineCommand(name: []const u8, params: []const ParamSchema, result: []const u8) CommandSchema {
    return .{ .name = name, .params = params, .result = result };
}

/// Produces a TypeScript `.d.ts` string from a slice of `CommandSchema`.
/// The caller owns the returned string and must free with the same allocator.
pub fn generateTypeScript(allocator: std.mem.Allocator, commands: []const CommandSchema) ![]u8 {
    var buf = try std.ArrayList(u8).initCapacity(allocator, 0);
    errdefer buf.deinit(allocator);

    try buf.appendSlice(allocator, "// Generated by zero-native bridge codegen. Do not edit.\n");
    try buf.appendSlice(allocator, "declare module \"zero-native\" {\n");

    for (commands) |cmd| {
        try buf.appendSlice(allocator, "  export function invoke(cmd: \"");
        try buf.appendSlice(allocator, cmd.name);
        try buf.appendSlice(allocator, "\", args: {");
        try writeArgsBody(allocator, &buf, cmd.params);
        try buf.appendSlice(allocator, "}): Promise<");
        try buf.appendSlice(allocator, cmd.result);
        try buf.appendSlice(allocator, ">;\n");
    }

    try buf.appendSlice(allocator, "}\n");

    return buf.toOwnedSlice(allocator);
}

/// Writes the interior of a TypeScript object type literal: `key: Type; key2?: Type2`.
/// Does NOT emit the surrounding braces.
fn writeArgsBody(allocator: std.mem.Allocator, buf: *std.ArrayList(u8), params: []const ParamSchema) !void {
    for (params, 0..) |param, i| {
        if (i > 0) try buf.appendSlice(allocator, "; ");
        try buf.appendSlice(allocator, param.name);
        if (param.optional) try buf.append(allocator, '?');
        try buf.appendSlice(allocator, ": ");
        try buf.appendSlice(allocator, param.type_name);
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

test "generateTypeScript with one command produces valid .d.ts" {
    const allocator = std.testing.allocator;
    const commands = [_]CommandSchema{
        defineCommand("add", &.{
            .{ .name = "a", .type_name = "number" },
            .{ .name = "b", .type_name = "number" },
        }, "number"),
    };

    const ts = try generateTypeScript(allocator, &commands);
    defer allocator.free(ts);

    try std.testing.expect(std.mem.indexOf(u8, ts, "declare module \"zero-native\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, ts, "export function invoke") != null);
    try std.testing.expect(std.mem.indexOf(u8, ts, "Promise<number>") != null);
}

test "multiple commands produce multiple overloads" {
    const allocator = std.testing.allocator;
    const commands = [_]CommandSchema{
        defineCommand("add", &.{
            .{ .name = "a", .type_name = "number" },
            .{ .name = "b", .type_name = "number" },
        }, "number"),
        defineCommand("greet", &.{
            .{ .name = "name", .type_name = "string" },
        }, "string"),
    };

    const ts = try generateTypeScript(allocator, &commands);
    defer allocator.free(ts);

    // Count occurrences of "export function invoke".
    var count: usize = 0;
    var pos: usize = 0;
    while (std.mem.indexOfPos(u8, ts, pos, "export function invoke")) |idx| {
        count += 1;
        pos = idx + 1;
    }
    try std.testing.expectEqual(@as(usize, 2), count);

    try std.testing.expect(std.mem.indexOf(u8, ts, "Promise<number>") != null);
    try std.testing.expect(std.mem.indexOf(u8, ts, "Promise<string>") != null);
}

test "void result generates Promise<void>" {
    const allocator = std.testing.allocator;
    const commands = [_]CommandSchema{
        defineCommand("shutdown", &.{}, "void"),
    };

    const ts = try generateTypeScript(allocator, &commands);
    defer allocator.free(ts);

    try std.testing.expect(std.mem.indexOf(u8, ts, "Promise<void>") != null);
}

test "escaped command names with dots work" {
    const allocator = std.testing.allocator;
    const commands = [_]CommandSchema{
        defineCommand("native.ping", &.{
            .{ .name = "source", .type_name = "string" },
        }, "object"),
    };

    const ts = try generateTypeScript(allocator, &commands);
    defer allocator.free(ts);

    try std.testing.expect(std.mem.indexOf(u8, ts, "\"native.ping\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, ts, "Promise<object>") != null);
}

test "empty params produce args: {}" {
    const allocator = std.testing.allocator;
    const commands = [_]CommandSchema{
        defineCommand("ping", &.{}, "string"),
    };

    const ts = try generateTypeScript(allocator, &commands);
    defer allocator.free(ts);

    try std.testing.expect(std.mem.indexOf(u8, ts, "args: {}") != null);
}

test "optional params emit ? suffix" {
    const allocator = std.testing.allocator;
    const commands = [_]CommandSchema{
        defineCommand("search", &.{
            .{ .name = "query", .type_name = "string" },
            .{ .name = "limit", .type_name = "number", .optional = true },
        }, "object"),
    };

    const ts = try generateTypeScript(allocator, &commands);
    defer allocator.free(ts);

    try std.testing.expect(std.mem.indexOf(u8, ts, "limit?: number") != null);
    try std.testing.expect(std.mem.indexOf(u8, ts, "query: string") != null);
}

test "defineCommand returns correct schema" {
    const cmd = defineCommand("add", &.{
        .{ .name = "a", .type_name = "number" },
        .{ .name = "b", .type_name = "number" },
    }, "number");

    try std.testing.expectEqualStrings("add", cmd.name);
    try std.testing.expectEqualStrings("number", cmd.result);
    try std.testing.expectEqual(@as(usize, 2), cmd.params.len);
    try std.testing.expectEqualStrings("a", cmd.params[0].name);
    try std.testing.expectEqualStrings("number", cmd.params[0].type_name);
}
