export const PAGE_TITLES: Record<string, string> = {
  "": "Build Desktop Apps\nwith Zig + WebView",
  "quick-start": "Quick Start",
  examples: "Examples",
  "app-model": "App Model",
  frontend: "Frontend Projects",
  windows: "Windows",
  webviews: "Multiple WebViews",
  bridge: "Bridge",
  "bridge/builtin-commands": "Builtin Commands",
  "bridge/codegen": "Type-Safe IPC (Codegen)",
  dialogs: "Dialogs",
  tray: "System Tray",
  security: "Security",
  sandbox: "App Sandbox",
  cli: "CLI Reference",
  "cli/dev": "Dev Server",
  packaging: "Packaging",
  "packaging/signing": "Code Signing",
  updates: "Updates",
  "app-zon": "app.zon Reference",
  manifest: "Manifest Reference",
  capabilities: "Capabilities",
  debugging: "Debugging",
  "debugging/doctor": "zero-native doctor",
  automation: "Automation",
  testing: "Testing",
  extensions: "Extensions",
  "extensions/plugins": "Bundled Plugins",
  "extensions/plugins/clipboard": "Plugin: Clipboard",
  "extensions/plugins/shell": "Plugin: Shell",
  "extensions/plugins/notification": "Plugin: Notification",
  "extensions/plugins/http": "Plugin: HTTP",
  "extensions/plugins/deep-link": "Plugin: Deep Link",
  "extensions/plugins/store": "Plugin: Store",
  "extensions/plugins/autostart": "Plugin: Autostart",
  "extensions/plugins/single-instance": "Plugin: Single Instance",
  "extensions/plugins/updater": "Plugin: Updater",
  "extensions/plugins/global-shortcut": "Plugin: Global Shortcut",
  "extensions/plugins/websocket": "Plugin: WebSocket",
  embed: "Embedded App",
  "web-engines": "Web Engines",
  packages: "Package Distribution",
  "api/runtime": "API: Runtime",
  "api/dispatcher": "API: Dispatcher",
  "api/channel": "API: Channel",
  "api/metadata": "API: Metadata",
  "api/capability": "API: Capability",
  "api/module-registry": "API: ModuleRegistry",
  "api/sandbox": "API: Sandbox",
};

export function getPageTitle(slug: string): string | null {
  return slug in PAGE_TITLES ? PAGE_TITLES[slug]! : null;
}
